import { Metadata } from "next";


export const metadata: Metadata = {
  title: {
    default:'next.js tutorial',
    template: '%s | Codevolution',
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="bg-blue">
          <p>Header</p>
        </header>
        {children}
        <footer>
          <p>Footer</p>
        </footer>
        </body>
    </html>
  )
}
